# Generated by Django 4.1.1 on 2022-11-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlist',
        ),
    ]
