# Generated by Django 4.1.3 on 2022-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=70)),
                ('rank', models.CharField(default='', max_length=70)),
                ('title', models.CharField(default='', max_length=70)),
                ('singer', models.CharField(default='', max_length=70)),
                ('type', models.CharField(default='', max_length=70)),
                ('lyrics', models.TextField(default='', max_length=500)),
                ('likes', models.CharField(default='', max_length=70)),
                ('image', models.TextField(default='', max_length=256)),
                ('genre', models.ManyToManyField(related_name='songs', to='songs.genre')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
