# Generated by Django 4.1.1 on 2022-11-03 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_likes',
            field=models.ManyToManyField(related_name='like_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
