# Generated by Django 4.1.1 on 2022-11-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_song_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
    ]
